// +build unit

package dementor

import (
	"fmt"
	"net/http"
	"net/http/httptest"
	"testing"
	"time"
)

func TestCreateProjectSuccess(t *testing.T) {
	var handler = http.HandlerFunc(func(rw http.ResponseWriter, req *http.Request) {
		rw.Header().Set("Content-Type", "application/json")
		fmt.Fprint(rw, `{"status":"success","path":"path","action":"redirect"}`)
	})
	ts := httptest.NewServer(handler)
	defer ts.Close()
	conf := Config
	conf.Url = ts.URL

	req := &CreateProjectReq{
		Name:        "Test" + time.Now().Format("2006-01-02T15-04-05"),
		Description: "Generated by a unit test.",
		CommonConf:  conf,
	}
	t.Logf("%+v", *req)
	res, err := CreateProject("sessionId", req)
	if err != nil {
		t.Fatal(err)
	}
	t.Logf("%+v", res)
}
